import { Book, SwapRequest, UserSubmission , UserRental, UserMessage} from "@/interfaces";

// Images
export const IMAGES = {
  hero: '/assets/images/hero-image.png',
};

export const mockSubmissions: UserSubmission[] = [
  {
    id: 'sub_001',
    bookTitle: 'The Great Gatsby',
    status: 'Pending Inspection',
    submittedDate: '2025-08-10T10:00:00Z',
  },
  {
    id: 'sub_002',
    bookTitle: 'Deep Work',
    status: 'Pending Inspection',
    submittedDate: '2025-08-09T14:30:00Z',
  },
  {
    id: 'sub_003',
    bookTitle: 'The Midnight Library',
    status: 'Accepted',
    submittedDate: '2025-08-05T11:00:00Z',
    creditValue: 850,
  },
  {
    id: 'sub_004',
    bookTitle: 'Pride and Prejudice',
    status: 'Rejected',
    submittedDate: '2025-08-04T09:00:00Z',
    rejectionReason: 'Water damage on cover',
  },
  {
    id: 'sub_005',
    bookTitle: 'The Design of Everyday Things',
    status: 'Accepted',
    submittedDate: '2025-08-01T16:20:00Z',
    payoutValue: 1100,
  },
];

export const mockRentals: UserRental[] = [
  {
    id: 'rent_001',
    bookTitle: 'The Lean Startup',
    imageUrl: '/assets/images/book-lean-startup.jpg',
    rentalDate: '2025-07-15T10:00:00Z',
    returnDate: '2025-08-15T10:00:00Z',
    status: 'Rented',
  },
  {
    id: 'rent_002',
    bookTitle: 'Clean Code',
    imageUrl: '/assets/images/book-clean-code.webp',
    rentalDate: '2025-07-01T11:30:00Z',
    returnDate: '2025-08-01T11:30:00Z',
    status: 'Overdue',
  },
  {
    id: 'rent_003',
    bookTitle: 'The Design of Everyday Things',
    imageUrl: '/assets/images/book-design-of-everyday-things.webp',
    rentalDate: '2025-05-20T09:00:00Z',
    returnDate: '2025-06-20T09:00:00Z',
    status: 'Returned',
  },
];

export const mockMessages: UserMessage[] = [
  {
    id: 'msg_001',
    subject: 'Update on your submission for "Pride and Prejudice"',
    lastMessage: 'Hi Circuit, we have received your book and it is now pending inspection. We will update you shortly.',
    lastMessageDate: '2025-08-11T09:30:00Z',
    isRead: false,
    relatedTo: 'Submission #sub_004'
  },
  {
    id: 'msg_002',
    subject: 'Your rental is due soon!',
    lastMessage: 'This is a friendly reminder that your rental for "Clean Code" is due in 3 days. Please see return instructions...',
    lastMessageDate: '2025-07-29T14:00:00Z',
    isRead: true,
  },
  {
    id: 'msg_003',
    subject: 'Welcome to The Circuit!',
    lastMessage: 'We are thrilled to have you join our community of readers. Let us know if you have any questions!',
    lastMessageDate: '2025-07-28T10:00:00Z',
    isRead: true,
  },
];

// Sample Books
export const mockBooks: Book[] = [
  {
    id: "1",
    title: "The Design of Everyday Things",
    author: "Don Norman",
    description: "The Design of Everyday Things is a best-selling book by cognitive scientist and usability engineer Donald Norman about how design serves as the communication between object and user, and how to optimize that conduit of communication in order to make the experience of using the object pleasurable.",
    condition: "Used - Good",
    imageUrl: "/assets/images/book-design-of-everyday-things.webp",
    price: 1200.00,
    isSwappable: true,
    isRentable: true,
    postedAt: "2024-10-01T10:00:00Z",
    tags: ['Bestseller', 'New Arrival'],
    availability: 'In Stock',
    genre: ['Tech'],
  },
  {
    id: "2",
    title: "The Midnight Library",
    author: "Matt Haig",
    description: "A novel about second chances and regrets.",
    condition: "used",
    imageUrl: "/assets/images/book-midnight-library.jpg",
    price: 1020.00,
    isSwappable: false,
    isRentable: false,
    postedAt: "2025-07-25T12:00:00Z",
    tags: ['Bestseller', 'New Arrival'],
    availability: 'In Stock',
    genre: ['Fiction', 'Classic'],
  },
  {
    id: "3",
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    description: "A classic children’s novel of mystery and healing.",
    condition: "used",
    imageUrl: "/assets/images/book-secret-garden.jpg",
    price: 8,
    isSwappable: true,
    isRentable: false,
    postedAt: "2025-07-28T15:30:00Z",
    tags: ['Bestseller', 'New Arrival'],
    availability: 'In Stock',
    genre: ['Fiction', 'Classic'],
  },
  {
    id: "4",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "A romantic novel that explores manners and marriage.",
    condition: "like new",
    imageUrl: "/assets/images/book-pride-prejudice.jpg",
    price: 9,
    isSwappable: false,
    isRentable: false,
    postedAt: "2025-07-20T09:00:00Z",
    tags: ['Bestseller', 'New Arrival'],
    availability: 'In Stock',
    genre: ['Fiction', 'Classic'],
  },
  {
    id: "5",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: "A novel by Harper Lee published in 1960. Instantly successful, it is a classic of modern American literature, winning the Pulitzer Prize.",
    condition: "Like New",
    imageUrl: "/assets/images/book-mockingbird.jpg",
    price: 1500.00,
    isSwappable: true,
    isRentable: false, // This one can't be rented
    postedAt: "2024-10-02T11:30:00Z",
    tags: ['Bestseller', 'New Arrival'],
    availability: 'In Stock',
    genre: ['Fiction', 'Classic'],
  },
  {
    id: "6",
    title: "1984",
    author: "George Orwell",
    description: "A dystopian novel on surveillance and control.",
    condition: "used",
    imageUrl: "/assets/images/book-1984.jpg",
    price: 932,
    isSwappable: true,
    isRentable: false,
    postedAt: "2025-07-18T14:00:00Z",
    tags: ['Bestseller', 'New Arrival'],
    availability: 'In Stock',
    genre: ['Fiction', 'Classic'],
  },
  {
    id: "7",
    title: "Atomic Habits",
    author: "James Clear",
    description: "Published in 1925, this novel explores themes of wealth, love, and the American Dream during the Roaring Twenties. It follows the enigmatic millionaire Jay Gatsby and his pursuit of Daisy Buchanan.",
    condition: "Used - Good",
    imageUrl: "/assets/images/book-atomic-habits.jpg",
    price: 1200.00,
    isSwappable: true,
    isRentable: true,
    postedAt: "2024-10-01T10:00:00Z",
    tags: ['Bestseller', 'New Arrival'],
    availability: 'In Stock',
    genre: ['Fiction', 'Classic'],
  },
  {
    id: "8",
    title: "Deep Work",
    author: "Cal Newport",
    description: "Rules for focused success in a distracted world. A practical guide for increasing productivity and mastering complex tasks.",
    condition: "Like New",
    imageUrl: "/assets/images/book-deep-work.png",
    price: 1100.00,
    isSwappable: true,
    isRentable: false,
    postedAt: "2025-07-29T08:00:00Z",
    tags: ['Bestseller'],
    availability: 'In Stock',
    genre: ['Business']
  },
  {
    id: "9",
    title: "Principles: Life and Work",
    author: "Ray Dalio",
    description: "Ray Dalio shares the unconventional principles that helped him create one of the world's largest hedge funds.",
    condition: "Used - Good",
    imageUrl: "/assets/images/book-principles.jpg",
    price: 980.00,
    isSwappable: false,
    isRentable: true,
    postedAt: "2025-06-15T10:30:00Z",
    tags: ['Bestseller'],
    availability: 'In Stock',
    genre: ['Business']
  },
  {
    id: "10",
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen",
    description: "A comprehensive textbook on algorithms covering a wide range of topics, often referred to as the 'bible' of algorithms.",
    condition: "Used - Acceptable",
    imageUrl: "/assets/images/book-intro-to-algorithms.webp",
    price: 2500.00,
    isSwappable: false,
    isRentable: true,
    postedAt: "2025-05-01T13:45:00Z",
    tags: ['New Arrival'],
    availability: 'In Stock',
    genre: ['Textbooks', 'Tech']
  },
  {
    id: "11",
    title: "Good to Great",
    author: "Jim Collins",
    description: "Why some companies make the leap to greatness and others don't. A deep dive into business transformation.",
    condition: "Used - Good",
    imageUrl: "/assets/images/book-good-to-great.jpg",
    price: 850.00,
    isSwappable: true,
    isRentable: false,
    postedAt: "2025-08-01T11:00:00Z",
    tags: ['Bestseller'],
    availability: 'In Stock',
    genre: ['Business']
  },
  {
    id: "12",
    title: "The Lean Startup",
    author: "Eric Ries",
    description: "A method for developing businesses and products through validated learning, rapid experimentation, and iterative releases.",
    condition: "Like New",
    imageUrl: "/assets/images/book-lean-startup.jpg",
    price: 950.00,
    isSwappable: false,
    isRentable: true,
    postedAt: "2025-06-12T08:45:00Z",
    tags: ['Bestseller'],
    availability: 'In Stock',
    genre: ['Business']
  },
  {
    id: "13",
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    description: "A self-improvement guide that presents a principle-centered approach for solving personal and professional problems.",
    condition: "Used - Good",
    imageUrl: "/assets/images/book-7-habits.webp",
    price: 780.00,
    isSwappable: true,
    isRentable: false,
    postedAt: "2025-07-21T15:10:00Z",
    tags: ['Bestseller'],
    availability: 'In Stock',
    genre: ['Business']
  },
  {
    id: "14",
    title: "Clean Code",
    author: "Robert C. Martin",
    description: "A handbook of agile software craftsmanship, teaching how to write readable, reusable, and refactorable code.",
    condition: "Like New",
    imageUrl: "/assets/images/book-clean-code.webp",
    price: 1600.00,
    isSwappable: false,
    isRentable: true,
    postedAt: "2025-08-10T09:25:00Z",
    tags: ['Bestseller'],
    availability: 'In Stock',
    genre: ['Tech']
  },
  {
    id: "15",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    description: "A sweeping narrative of humanity's creation and evolution that explores how Homo sapiens came to dominate the world. It challenges everything we thought we knew about being human.",
    condition: "Like New",
    imageUrl: "/assets/images/book-sapiens.webp",
    price: 1300.00,
    isSwappable: true,
    isRentable: true,
    postedAt: "2025-08-11T14:20:00Z",
    tags: ['Bestseller'],
    availability: 'In Stock',
    genre: ['Fiction'] 
  },
  {
    id: "16",
    title: "The Pragmatic Programmer",
    author: "David Thomas, Andrew Hunt",
    description: "This book is a collection of tips to improve the development process, focusing on practical advice from career software developers. It covers topics from personal responsibility to architectural techniques.",
    condition: "Used - Acceptable",
    imageUrl: "/assets/images/book-pragmatic-programmer.webp",
    price: 1450.00,
    isSwappable: true,
    isRentable: false,
    postedAt: "2025-07-30T16:00:00Z",
    tags: [],
    availability: 'In Stock',
    genre: ['Tech']
  },
  {
    id: "17",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    description: "Nobel laureate Daniel Kahneman explains the two systems that drive the way we think, one fast and intuitive, and the other slow and logical. It reveals where we can and cannot trust our intuitions.",
    condition: "Used - Good",
    imageUrl: "/assets/images/book-thinking-fast-slow.webp",
    price: 1150.00,
    isSwappable: true,
    isRentable: true,
    postedAt: "2025-08-08T11:45:00Z",
    tags: ['Bestseller'],
    availability: 'In Stock',
    genre: ['Business']
  },
  {
    id: "18",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    description: "An epic high-fantasy novel that chronicles the great quest to destroy the One Ring and defeat the Dark Lord Sauron. It's a timeless tale of fellowship, courage, and the battle between good and evil.",
    condition: "Like New",
    imageUrl: "/assets/images/book-lord-of-the-rings.webp",
    price: 1800.00,
    isSwappable: true,
    isRentable: false,
    postedAt: "2025-08-12T09:00:00Z",
    tags: ['Bestseller'],
    availability: 'In Stock',
    genre: ['Fiction']
  },
  {
    id: "19",
    title: "Don't Make Me Think, Revisited",
    author: "Steve Krug",
    description: "A foundational book on web usability that champions common sense and clarity in design. It provides essential principles for making websites and applications intuitive for users.",
    condition: "Used - Good",
    imageUrl: "/assets/images/book-dont-make-me-think.webp",
    price: 1050.00,
    isSwappable: true,
    isRentable: true,
    postedAt: "2025-08-02T18:00:00Z",
    tags: [],
    availability: 'In Stock',
    genre: ['Tech']
  },
  {
    id: "20",
    title: "Zero to One",
    author: "Peter Thiel",
    description: "Notes on startups, or how to build the future, arguing that progress comes from monopoly, not competition. It's a compelling look at how to create new things.",
    condition: "Like New",
    imageUrl: "/assets/images/book-zero-to-one.webp",
    price: 900.00,
    isSwappable: false,
    isRentable: false,
    postedAt: "2025-08-09T13:15:00Z",
    tags: ['Bestseller'],
    availability: 'In Stock',
    genre: ['Business']
  },
];
