import { Book, SwapRequest } from "@/interfaces";

// Images
export const IMAGES = {
  hero: '/assets/images/hero-image.png',
};

// Sample Books
export const mockBooks: Book[] = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: "Published in 1925, this novel explores themes of wealth, love, and the American Dream during the Roaring Twenties. It follows the enigmatic millionaire Jay Gatsby and his pursuit of Daisy Buchanan.",
    condition: "Used - Good",
    imageUrl: "/assets/images/book-atomic-habits.png",
    price: 1200.00,
    isSwappable: true,
    isRentable: true,
    postedAt: "2024-10-01T10:00:00Z",
    tags: ['Bestseller', 'New Arrival'],
    availability: 'In Stock',
    genre: ['Fiction', 'Classic'],
  },
  {
    id: "2",
    title: "The Midnight Library",
    author: "Matt Haig",
    description: "A novel about second chances and regrets.",
    condition: "used",
    imageUrl: "/assets/images/book-midnight-library.jpg",
    price: 1020.00,
    isSwappable: false,
    isRentable: false,
    postedAt: "2025-07-25T12:00:00Z",
    tags: ['Bestseller', 'New Arrival'],
    availability: 'In Stock',
    genre: ['Fiction', 'Classic'],
  },
  {
    id: "3",
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    description: "A classic children’s novel of mystery and healing.",
    condition: "used",
    imageUrl: "/assets/images/book-secret-garden.jpg",
    price: 8,
    isSwappable: true,
    isRentable: false,
    postedAt: "2025-07-28T15:30:00Z",
    tags: ['Bestseller', 'New Arrival'],
    availability: 'In Stock',
    genre: ['Fiction', 'Classic'],
  },
  {
    id: "4",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "A romantic novel that explores manners and marriage.",
    condition: "like new",
    imageUrl: "/assets/images/book-pride-prejudice.jpg",
    price: 9,
    isSwappable: false,
    isRentable: false,
    postedAt: "2025-07-20T09:00:00Z",
    tags: ['Bestseller', 'New Arrival'],
    availability: 'In Stock',
    genre: ['Fiction', 'Classic'],
  },
  {
    id: "5",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: "A novel by Harper Lee published in 1960. Instantly successful, it is a classic of modern American literature, winning the Pulitzer Prize.",
    condition: "Like New",
    imageUrl: "/assets/images/book-mockingbird.png",
    price: 1500.00,
    isSwappable: true,
    isRentable: false, // This one can't be rented
    postedAt: "2024-10-02T11:30:00Z",
    tags: ['Bestseller', 'New Arrival'],
    availability: 'In Stock',
    genre: ['Fiction', 'Classic'],
  },
  {
    id: "6",
    title: "1984",
    author: "George Orwell",
    description: "A dystopian novel on surveillance and control.",
    condition: "used",
    imageUrl: "/assets/images/book-1984.jpg",
    price: 932,
    isSwappable: true,
    isRentable: false,
    postedAt: "2025-07-18T14:00:00Z",
    tags: ['Bestseller', 'New Arrival'],
    availability: 'In Stock',
    genre: ['Fiction', 'Classic'],
  },
];
